NICHES: dict = {
    "metalurgia": {
        "name": "Metalúrgica",
        "emoji": "⚙️",
        "description": "Siderurgia, fundição e processamento de metais",
        "keywords_trends": ["metalurgia", "siderurgia brasil"],
        "keywords_news": '"indústria metalúrgica" OR "siderurgia brasileira" OR "processamento de metais" OR "fundição de aço"',
        "keywords_arxiv": "metallurgy OR steelmaking OR metal processing OR smelting",
        "color": "#94A3B8",
        "category": "Materiais",
    },
    "transporte": {
        "name": "Transporte",
        "emoji": "🚢",
        "description": "Dutos, logística industrial e transporte de fluidos",
        "keywords_trends": ["oleoduto brasil", "transporte industrial"],
        "keywords_news": '"oleoduto" OR "transporte de combustível" OR "logística industrial" OR "dutoviário"',
        "keywords_arxiv": "pipeline transport OR fluid transport OR pipeline engineering",
        "color": "#64748B",
        "category": "Processos Industriais",
    },
    "textil": {
        "name": "Têxtil",
        "emoji": "🧵",
        "description": "Fibras, tingimento e acabamento têxtil",
        "keywords_trends": ["industria têxtil", "fibras sintéticas"],
        "keywords_news": '"indústria têxtil" OR "fibras sintéticas" OR "tingimento de tecidos" OR "setor têxtil"',
        "keywords_arxiv": "textile fiber OR dyeing process OR textile engineering OR synthetic fiber",
        "color": "#EC4899",
        "category": "Processos Industriais",
    },
    "borracha_latex": {
        "name": "Borracha e Látex",
        "emoji": "⚫",
        "description": "Elastômeros, vulcanização e borracha sintética",
        "keywords_trends": ["borracha sintética", "látex natural"],
        "keywords_news": '"borracha sintética" OR "látex natural" OR "vulcanização" OR "setor de borracha"',
        "keywords_arxiv": "rubber vulcanization OR latex elastomer OR synthetic rubber OR rubber processing",
        "color": "#F59E0B",
        "category": "Materiais",
    },
    "oleos_gorduras": {
        "name": "Óleos e Gorduras",
        "emoji": "🫙",
        "description": "Oleoquímica, refino de óleos e gorduras vegetais",
        "keywords_trends": ["óleo vegetal", "oleoquímica"],
        "keywords_news": '"óleo vegetal" OR "oleoquímica" OR "refino de óleos" OR "gordura vegetal"',
        "keywords_arxiv": "vegetable oil refining OR oleochemical OR fat processing OR palm oil",
        "color": "#FBBF24",
        "category": "Alimentos e Agro",
    },
    "energia": {
        "name": "Energia",
        "emoji": "⚡",
        "description": "Energias renováveis, geração e armazenamento de energia",
        "keywords_trends": ["energia renovável brasil", "hidrogênio verde"],
        "keywords_news": '"energia renovável" OR "hidrogênio verde" OR "armazenamento de energia" OR "transição energética"',
        "keywords_arxiv": "renewable energy OR green hydrogen OR energy storage OR bioenergy",
        "color": "#10B981",
        "category": "Energia",
    },
    "gases_industriais": {
        "name": "Gases Industriais",
        "emoji": "💨",
        "description": "Produção, separação e aplicação de gases industriais",
        "keywords_trends": ["gases industriais", "nitrogênio industrial"],
        "keywords_news": '"gases industriais" OR "separação de gases" OR "nitrogênio industrial" OR "oxigênio industrial"',
        "keywords_arxiv": "gas separation OR industrial gas OR cryogenic separation OR nitrogen production",
        "color": "#06B6D4",
        "category": "Energia",
    },
    "alimentos": {
        "name": "Alimentos",
        "emoji": "🍃",
        "description": "Processamento, conservação e desenvolvimento de alimentos",
        "keywords_trends": ["processamento alimentos", "food tech brasil"],
        "keywords_news": '"processamento de alimentos" OR "indústria alimentícia" OR "tecnologia de alimentos" OR "food tech"',
        "keywords_arxiv": "food processing OR food technology OR food preservation OR food engineering",
        "color": "#F97316",
        "category": "Alimentos e Agro",
    },
    "resinas_colas": {
        "name": "Resinas e Colas",
        "emoji": "🧪",
        "description": "Adesivos, resinas epóxi e formulação de ligantes",
        "keywords_trends": ["resinas epóxi", "adesivos industriais"],
        "keywords_news": '"resinas epóxi" OR "adesivos industriais" OR "formulação de resinas" OR "mercado de adesivos"',
        "keywords_arxiv": "epoxy resin OR adhesive formulation OR polymer adhesive OR binder resin",
        "color": "#84CC16",
        "category": "Materiais",
    },
    "industria_quimica": {
        "name": "Indústria Química",
        "emoji": "🏭",
        "description": "Química fina, petroquímica e processos químicos gerais",
        "keywords_trends": ["química fina", "petroquímica brasil"],
        "keywords_news": '"indústria química" OR "petroquímica" OR "química fina" OR "processos químicos"',
        "keywords_arxiv": "chemical industry OR petrochemical OR fine chemicals OR chemical process engineering",
        "color": "#0EA5E9",
        "category": "Processos Industriais",
    },
    "polimeros": {
        "name": "Polímeros",
        "emoji": "🔬",
        "description": "Plásticos, biopolímeros e novos materiais poliméricos",
        "keywords_trends": ["polímeros brasil", "bioplástico"],
        "keywords_news": '"polímeros" OR "bioplástico" OR "plástico biodegradável" OR "indústria de plásticos"',
        "keywords_arxiv": "polymer synthesis OR biopolymer OR plastic processing OR polymer engineering",
        "color": "#8B5CF6",
        "category": "Materiais",
    },
    "papel_celulose": {
        "name": "Papel e Celulose",
        "emoji": "📄",
        "description": "Produção de celulose, papel e biomassa lignocelulósica",
        "keywords_trends": ["papel celulose brasil", "celulose eucalipto"],
        "keywords_news": '"celulose" OR "indústria de papel" OR "eucalipto celulose" OR "processo kraft"',
        "keywords_arxiv": "pulp paper OR cellulose processing OR kraft process OR lignocellulosic biomass",
        "color": "#CA8A04",
        "category": "Sustentabilidade",
    },
    "residuos": {
        "name": "Resíduos",
        "emoji": "♻️",
        "description": "Tratamento de resíduos, economia circular e efluentes",
        "keywords_trends": ["tratamento resíduos", "economia circular brasil"],
        "keywords_news": '"resíduos industriais" OR "tratamento de efluentes" OR "economia circular" OR "reciclagem industrial"',
        "keywords_arxiv": "waste treatment OR circular economy OR industrial effluent OR waste recycling",
        "color": "#22C55E",
        "category": "Sustentabilidade",
    },
    "biotecnologia": {
        "name": "Biotecnologia",
        "emoji": "🧬",
        "description": "Bioprocessos, fermentação industrial e engenharia bioquímica",
        "keywords_trends": ["biotecnologia industrial", "fermentação industrial"],
        "keywords_news": '"biotecnologia industrial" OR "bioprocesso" OR "fermentação industrial" OR "biorreatores"',
        "keywords_arxiv": "bioprocess engineering OR industrial fermentation OR bioreactor OR enzyme engineering",
        "color": "#7C3AED",
        "category": "Biotecnologia",
    },
    "combustiveis": {
        "name": "Combustíveis",
        "emoji": "⛽",
        "description": "Etanol, biodiesel, refino e combustíveis alternativos",
        "keywords_trends": ["etanol brasil", "biodiesel"],
        "keywords_news": '"etanol" OR "biodiesel" OR "combustíveis alternativos" OR "refino de petróleo"',
        "keywords_arxiv": "biodiesel production OR ethanol fuel OR biofuel OR fuel refinery",
        "color": "#EF4444",
        "category": "Energia",
    },
    "lubrificantes": {
        "name": "Lubrificantes",
        "emoji": "🔩",
        "description": "Óleos lubrificantes, graxas e fluidos industriais",
        "keywords_trends": ["lubrificantes industriais", "óleo lubrificante"],
        "keywords_news": '"lubrificantes industriais" OR "óleos lubrificantes" OR "graxas industriais" OR "fluidos de corte"',
        "keywords_arxiv": "lubricant oil OR lubrication engineering OR tribology OR grease formulation",
        "color": "#78716C",
        "category": "Processos Industriais",
    },
    "agroindustria": {
        "name": "Agroindústria",
        "emoji": "🌾",
        "description": "Processamento de cana, soja, milho e derivados agrícolas",
        "keywords_trends": ["agroindústria brasil", "cana de açúcar"],
        "keywords_news": '"agroindústria" OR "cana-de-açúcar" OR "processamento de soja" OR "setor sucroenergético"',
        "keywords_arxiv": "sugarcane processing OR soybean processing OR agroindustry OR agricultural biorefinery",
        "color": "#65A30D",
        "category": "Alimentos e Agro",
    },
    "tintas": {
        "name": "Tintas e Revestimentos",
        "emoji": "🎨",
        "description": "Tintas, vernizes, pigmentos e revestimentos anticorrosivos",
        "keywords_trends": ["tintas industriais", "revestimentos anticorrosivos"],
        "keywords_news": '"tintas industriais" OR "revestimentos anticorrosivos" OR "mercado de tintas" OR "vernizes industriais"',
        "keywords_arxiv": "paint coating OR anticorrosion coating OR surface coating OR pigment formulation",
        "color": "#E11D48",
        "category": "Materiais",
    },
}
